# -*- coding: utf-8 -*-
"""Untitled267.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sYyaIQWyg6D5CnQM8-Xu85ab81JVfpNl
"""

import pandas as pd
url = "https://raw.githubusercontent.com/Premalatha-success/Datasets/refs/heads/main/AutoInsurance.csv"
df = pd.read_csv(url)
df.head()

df = df.drop(['Customer'], axis=1, errors='ignore')  # ignore errors if 'Customer' not present
# As per df.isnull().sum(), there are no missing values in the dataset, so no fillna is needed.
# Encode categorical variables

categorical_cols = df.select_dtypes(include='object').columns
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
# Verify
df.head()

# The 'Customer Lifetime Value' column already exists in the dataset and is likely the target variable.
# Therefore, we will directly assign it to 'CLV'.
df['CLV'] = df['Customer Lifetime Value']
# Verify the new 'CLV' column
print(df[['Customer Lifetime Value', 'CLV']].head())

X = df.drop('CLV', axis=1)
y = df['CLV']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3
)

from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

lr_model.score(X_train, y_train)

